apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth2factor-deployment
spec:
  selector:
    matchLabels:
      app: auth2factor
  replicas: 1
  template:
    metadata:
      labels:
        app: auth2factor
    spec:
      containers:
        - name: auth2factor
          image: adama93/auth2factor
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
